language: php
jobs:
  fast_finish: true
  include:
    - php: 7.1
      env: COVERAGE=1
    - php: 7.4
    - php: 8.0
before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
  - sh -c "if [ '$COVERAGE' ]; then curl --compressed --insecure -Ls -o /tmp/ocular.phar https://scrutinizer-ci.com/ocular.phar; fi"
script:
  - sh -c "if [ '$COVERAGE' ]; then phpdbg -qrr ./vendor/bin/phpunit --coverage-clover /tmp/clover.xml; else ./vendor/bin/phpunit; fi"
after_script:
  - sh -c "if [ '$COVERAGE' ]; then php /tmp/ocular.phar code-coverage:upload --format=php-clover /tmp/clover.xml; fi"