language: php
jobs:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
before_script:
  - phpenv config-rm xdebug.ini
  - composer install
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.1' ]; then curl -s -o /tmp/ocular.phar https://scrutinizer-ci.com/ocular.phar; fi"
script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.1' ]; then phpdbg -qrr ./vendor/bin/phpunit --coverage-clover /tmp/clover.xml; else ./vendor/bin/phpunit; fi"
after_script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.1' ]; then php /tmp/ocular.phar code-coverage:upload --format=php-clover /tmp/clover.xml; fi"