name: Tests

on:
  push:
    branches: [ master, Workarounds ]
  pull_request:
    branches: [ master ]

jobs:
  outdated-8-1-2:
    runs-on: ubuntu-latest
    container: amd64/php:8.1.26

    strategy:
      matrix:
        php-version:
          - "8.1"

    steps:
    - uses: "actions/checkout@v3"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: php-outdated

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test
